version: '3'
services:

  web:
    build: .
    dns:
     - 8.8.8.8
     - 114.114.114.114
    # ports:
    #  - "5000:5000"
    network_mode: "host"

  redis:
    image: "redis:alpine"
    network_mode: "host"

