version: '3'
services:

  web:
    build: .
    volumes:
      - /root/web:/code
    environment:
      - TZ=Asia/Shanghai
    ports:
     - "5000:5000"
    command: python app.py

  redis:
    image: "redis:alpine"

