version: '3'
services:

  web:
    build: .
    volumes:
      - /root/web:/code
    ports:
     - "5000:5000"
    command: echo "pwd:" && pwd && ls && python app.py

  redis:
    image: "redis:alpine"

