version: '3'
services:

  web:
    build: .
    volumes:
      - /root/web:/code
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
     - "5000:5000"
    command: python app.py

  redis:
    image: "redis:alpine"

